### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by wb2424** [mheller3000/MineTrekMod#6]
How the heck do I use this in my Minecraft instance...

**Comment by mheller3000** [comment]
I have just now uploaded the first public release version to the release tab in the github for download and use.  Download and place in your mods folder make sure you have the latest version of Forge installed and enjoy. :D <3

**Comment by wb2424** [comment]
Thank you so much! I admire your server and I hope to one day be a part of
it!

**Comment by wb2424** [comment]
Do you have any contact info for future problems?

**Comment by mheller3000** [comment]
We have a discord channel you can join to talk with us and submit questions etc.  
https://discord.gg/45XMja

**Comment by wb2424** [comment]
Thank you very much!

**Comment by mheller3000** [comment]
Sure Thing :D <3
